version: '2'

services:
    laravel:
        container_name: web-box-${project_name}
        image: web-image-${project_name}
        build:
            context: .
            dockerfile: ./docker/laravel/Dockerfile
            args:
                - PROJECT_NAME=${project_name}
        volumes:
            - ./:/var/www/
            - node_modules:/var/www/html/node_modules
        ports:
            - "80:80"
        entrypoint: ["/usr/local/sbin/start.sh"]
volumes:
    node_modules:
