version: '3'

services:
    laravel:
        container_name: web-box-${project_name}
        image: web-image-${project_name}
        build:
            context: .
            dockerfile: ./docker/laravel/Dockerfile
            args:
                - PROJECT_NAME=${project_name}
        volumes:
            - ./:/var/www/
        depends_on:
            - mysql-service
        ports:
            - "${APACHE_PORT:-80}:80"
            - "${APACHE_SSL_PORT:-443}:443"
        entrypoint: "/usr/local/sbin/start.sh"

    mysql-service:
        container_name: mysql-box-${project_name}
        image: mysql-image-${project_name}
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: docker
        ports:
            - "${MYSQL_PORT:-3306}:3306"
        networks:
            - default
